version: '3'
services:
  db:
    image: mysql/mysql-server:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'login_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'passwd'
      MYSQL_ROOT_PASSWORD: 'passwd'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - login:/var/lib/mysql
volumes:
  login:

